install:
  - mvn clean; java -version
script:
  - travis_wait 30 travis-scripts/jbossws-test.sh $SERVER_VERSION $BUILD_WFLY_MASTER

language: java
jdk:
  - openjdk8
  - openjdk11

env:
  - SERVER_VERSION=wildfly1700 BUILD_WFLY_MASTER=false
  - SERVER_VERSION=wildfly1800 BUILD_WFLY_MASTER=false
  - SERVER_VERSION=wildfly1900 BUILD_WFLY_MASTER=true

cache:
 directories:
  - $HOME/.m2
