install:
  - mvn clean; java -version
script:
  - travis_wait 30 travis-scripts/jbossws-test.sh $SERVER_VERSION $SECURITY_MGR $BUILD_WFLY_MASTER $USE_ELYTRON_PROFILE

language: java
jdk:
  - oraclejdk11

env:
  - SERVER_VERSION=wildfly1400 SECURITY_MGR=false BUILD_WFLY_MASTER=true USE_ELYTRON_PROFILE=false
  - SERVER_VERSION=wildfly1400 SECURITY_MGR=false BUILD_WFLY_MASTER=true USE_ELYTRON_PROFILE=true
  - SERVER_VERSION=wildfly1400,secmgr SECURITY_MGR=true BUILD_WFLY_MASTER=true USE_ELYTRON_PROFILE=false
  - SERVER_VERSION=wildfly1400,secmgr SECURITY_MGR=true BUILD_WFLY_MASTER=true USE_ELYTRON_PROFILE=true
cache:
 directories:
  - $HOME/.m2
